# Generated by Django 5.2.8 on 2026-01-03 15:54

import datetime
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(blank=True, editable=False, max_length=255, unique=True)),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_in_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('customer', models.ForeignKey(help_text='Customer who placed the order', on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to='crm.customer')),
                ('order_by', models.ForeignKey(help_text='User who placed the order', on_delete=django.db.models.deletion.PROTECT, related_name='orderorder_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order Delivery',
                'verbose_name_plural': 'Order Deliveries',
                'ordering': ['-order_date', 'order_number'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift', models.CharField(choices=[('MORNING', 'MORNING'), ('EVENING', 'EVENING')], help_text='Shift: M (Morning) or E (Evening)', max_length=50)),
                ('quantity_in_ctn', models.IntegerField(default=0, help_text='Quantity in carton')),
                ('quantity_in_pcs', models.IntegerField(default=0, help_text='Quantity in pieces')),
                ('advanced_in_ctn', models.IntegerField(default=0, help_text='Advanced quantity in carton')),
                ('advanced_in_pcs', models.IntegerField(default=0, help_text='Advanced quantity in pieces')),
                ('damaged_in_ctn', models.IntegerField(default=0, help_text='Damaged quantity in carton')),
                ('damaged_in_pcs', models.IntegerField(default=0, help_text='Damaged quantity in pieces')),
                ('order', models.ForeignKey(help_text='Order this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.orderdelivery')),
                ('price', models.ForeignKey(help_text='Price in this order item', on_delete=django.db.models.deletion.PROTECT, related_name='order_items_by_price', to='product.productprice')),
                ('product', models.ForeignKey(help_text='Product in this order item', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='product.product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['order', 'product'],
            },
        ),
    ]
