# Generated by Django 5.2.8 on 2026-01-03 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdelivery',
            name='commission_in_percentage',
        ),
    ]
