# Generated by Django 5.2.8 on 2026-01-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_orderdelivery_commission_in_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdelivery',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total amount (can be negative for returns/refunds)', max_digits=12),
        ),
    ]
