# Generated by Django 5.2.8 on 2026-01-04 17:23

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_customer_have_special_discount_and_more'),
        ('product', '0003_alter_product_sku'),
        ('sales', '0003_alter_orderdelivery_total_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_id', models.CharField(blank=True, editable=False, help_text='Unique identifier for the sales collection (auto-generated)', max_length=150, unique=True)),
                ('sales_date', models.DateField(default=datetime.date.today, help_text='Date of the sale')),
                ('total_sale', models.DecimalField(decimal_places=2, default=0.0, help_text='Total sale amount', max_digits=12)),
                ('commission_in_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Commission in percentage', max_digits=12)),
                ('special_discount_in_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Special discount in percentage', max_digits=12)),
                ('collection_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount collected', max_digits=12)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount due', max_digits=12)),
                ('collection_by_personal_loan', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount collected by personal loan', max_digits=12)),
                ('deduction_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='Deduction percentage in percentage', max_digits=5)),
                ('customer', models.ForeignKey(help_text='Customer for this sale', on_delete=django.db.models.deletion.PROTECT, related_name='customer_sales_collections', to='crm.customer')),
                ('sales_by', models.ForeignKey(help_text='User who made the sale', on_delete=django.db.models.deletion.PROTECT, related_name='sales_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Collection',
                'verbose_name_plural': 'Sales Collections',
                'ordering': ['-sales_date', 'sales_id'],
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_cnt_qtn', models.IntegerField(default=0, help_text='Carton quantity')),
                ('order_pcs_qtn', models.IntegerField(default=0, help_text='Pieces quantity')),
                ('damage_cnt_qtn', models.IntegerField(default=0, help_text='Damaged carton quantity')),
                ('damage_pcs_qtn', models.IntegerField(default=0, help_text='Damaged pieces quantity')),
                ('free_cnt_qtn', models.IntegerField(default=0, help_text='Free carton quantity')),
                ('free_pcs_qtn', models.IntegerField(default=0, help_text='Free pieces quantity')),
                ('price', models.ForeignKey(help_text='Price for this collection item', on_delete=django.db.models.deletion.PROTECT, related_name='collection_items_by_price', to='product.productprice')),
                ('product', models.ForeignKey(help_text='Product in this collection item', on_delete=django.db.models.deletion.PROTECT, related_name='collection_items', to='product.product')),
                ('sales', models.ForeignKey(help_text='Sales collection this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salescollection')),
            ],
            options={
                'verbose_name': 'Collection Item',
                'verbose_name_plural': 'Collection Items',
                'ordering': ['sales', 'product'],
            },
        ),
    ]
