# Generated by Django 5.2.8 on 2026-01-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_salescollection_collectionitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdelivery',
            name='customer',
        ),
    ]
