# Generated by Django 5.2.8 on 2026-01-26 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_orderdelivery_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectionItem',
        ),
    ]
