# Generated by Django 5.2.8 on 2026-01-26 15:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_sku'),
        ('sales', '0006_delete_collectionitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cnt_qtn', models.IntegerField(default=0, help_text='Carton quantity')),
                ('pcs_qtn', models.IntegerField(default=0, help_text='Pieces quantity')),
                ('price', models.ForeignKey(help_text='Price for this damage item', on_delete=django.db.models.deletion.PROTECT, related_name='damage_items_by_price', to='product.productprice')),
                ('product', models.ForeignKey(help_text='Product in this damage item', on_delete=django.db.models.deletion.PROTECT, related_name='damage_items', to='product.product')),
                ('sales', models.ForeignKey(help_text='Sales collection this damage item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='damage_items', to='sales.salescollection')),
            ],
            options={
                'verbose_name': 'Damage Item',
                'verbose_name_plural': 'Damage Items',
                'ordering': ['sales', 'product'],
            },
        ),
        migrations.CreateModel(
            name='FreeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cnt_qtn', models.IntegerField(default=0, help_text='Carton quantity')),
                ('pcs_qtn', models.IntegerField(default=0, help_text='Pieces quantity')),
                ('price', models.ForeignKey(help_text='Price for this free item', on_delete=django.db.models.deletion.PROTECT, related_name='free_items_by_price', to='product.productprice')),
                ('product', models.ForeignKey(help_text='Product in this free item', on_delete=django.db.models.deletion.PROTECT, related_name='free_items', to='product.product')),
                ('sales', models.ForeignKey(help_text='Sales collection this free item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='free_items', to='sales.salescollection')),
            ],
            options={
                'verbose_name': 'Free Item',
                'verbose_name_plural': 'Free Items',
                'ordering': ['sales', 'product'],
            },
        ),
    ]
