# Generated by Django 5.2.8 on 2026-01-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_damageitem_freeitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salescollection',
            name='due_amount',
        ),
        migrations.AlterField(
            model_name='salescollection',
            name='deduction_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Deduction percentage in percentage', max_digits=5),
        ),
    ]
