# Generated by Django 5.2.8 on 2026-01-26 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_remove_salescollection_due_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salescollection',
            name='collection_by_personal_loan',
        ),
    ]
