# Generated by Django 5.2.8 on 2026-01-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_remove_salescollection_collection_by_personal_loan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salescollection',
            name='deduction_percentage',
        ),
        migrations.AddField(
            model_name='damageitem',
            name='deduction_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Deduction percentage in percentage', max_digits=5),
        ),
    ]
