# Generated by Django 5.2.8 on 2026-01-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_remove_salescollection_deduction_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='damaged_in_ctn',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='damaged_in_pcs',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_in_ctn',
            field=models.IntegerField(default=0, help_text='Return quantity in carton'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_in_pcs',
            field=models.IntegerField(default=0, help_text='Return quantity in pieces'),
        ),
    ]
