# Generated by Django 5.2.8 on 2026-02-04 01:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_sku'),
        ('sales', '0011_remove_orderitem_damaged_in_ctn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_in_ctn', models.IntegerField(default=0, help_text='Damaged quantity in carton')),
                ('quantity_in_pcs', models.IntegerField(default=0, help_text='Damaged quantity in pieces')),
                ('damage_reason', models.TextField(blank=True, help_text='Reason for the damage', null=True)),
                ('order', models.ForeignKey(help_text='Order this damaged item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='damage_items', to='sales.orderdelivery')),
                ('price', models.ForeignKey(help_text='Price in this damaged order item', on_delete=django.db.models.deletion.PROTECT, related_name='damage_order_items_by_price', to='product.productprice')),
                ('product', models.ForeignKey(help_text='Product in this damaged order item', on_delete=django.db.models.deletion.PROTECT, related_name='damage_order_items', to='product.product')),
            ],
            options={
                'verbose_name': 'Damage Order Item',
                'verbose_name_plural': 'Damage Order Items',
                'ordering': ['order', 'product'],
            },
        ),
        migrations.CreateModel(
            name='FreeOfferItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_in_ctn', models.IntegerField(default=0, help_text='Free offer quantity in carton')),
                ('quantity_in_pcs', models.IntegerField(default=0, help_text='Free offer quantity in pieces')),
                ('order', models.ForeignKey(help_text='Order this free offer item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='free_offer_items', to='sales.orderdelivery')),
                ('price', models.ForeignKey(help_text='Price in this free offer item', on_delete=django.db.models.deletion.PROTECT, related_name='free_offer_order_items_by_price', to='product.productprice')),
                ('product', models.ForeignKey(help_text='Product in this free offer item', on_delete=django.db.models.deletion.PROTECT, related_name='free_offer_order_items', to='product.product')),
            ],
            options={
                'verbose_name': 'Free Offer Item',
                'verbose_name_plural': 'Free Offer Items',
                'ordering': ['order', 'product'],
            },
        ),
    ]
