# Generated by Django 5.2.8 on 2026-02-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_damageorderitem_freeofferitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdelivery',
            name='narration',
            field=models.TextField(blank=True, help_text='Additional notes or narration for the order', null=True),
        ),
    ]
