# Generated by Django 5.2.8 on 2026-02-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_orderdelivery_narration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdelivery',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='cash_sell_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cash sell amount for the order', max_digits=12),
        ),
    ]
