# Generated by Django 5.2.8 on 2026-02-04 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_remove_orderdelivery_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freeitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='freeitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='freeitem',
            name='sales',
        ),
        migrations.RemoveField(
            model_name='salescollection',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='salescollection',
            name='sales_by',
        ),
        migrations.DeleteModel(
            name='DamageItem',
        ),
        migrations.DeleteModel(
            name='FreeItem',
        ),
        migrations.DeleteModel(
            name='SalesCollection',
        ),
    ]
