# Generated by Django 5.2.8 on 2026-02-04 08:50

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_customer_zone_customer_area_and_more'),
        ('sales', '0015_remove_freeitem_price_remove_freeitem_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DueCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection_date', models.DateField(default=datetime.date.today, help_text='Date of the collection')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Collected amount', max_digits=12)),
                ('note', models.TextField(blank=True, help_text='Additional notes about this collection', null=True)),
                ('collected_by', models.ForeignKey(help_text='User who collected the payment', on_delete=django.db.models.deletion.PROTECT, related_name='received_due_collections', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer who is paying the due amount', on_delete=django.db.models.deletion.PROTECT, related_name='due_collections', to='crm.customer')),
            ],
            options={
                'verbose_name': 'Due Collection',
                'verbose_name_plural': 'Due Collections',
                'ordering': ['-collection_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DueSell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale_date', models.DateField(default=datetime.date.today, help_text='Date of the sale')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Due amount for this sell', max_digits=12)),
                ('note', models.TextField(blank=True, help_text='Additional notes about this due sell', null=True)),
                ('customer', models.ForeignKey(help_text='Customer for this due sell', on_delete=django.db.models.deletion.PROTECT, related_name='due_sells', to='crm.customer')),
                ('deliver_by', models.ForeignKey(help_text='User who delivered the goods', on_delete=django.db.models.deletion.PROTECT, related_name='delivered_due_sells', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Due Sell',
                'verbose_name_plural': 'Due Sells',
                'ordering': ['-sale_date', '-created_at'],
            },
        ),
    ]
