# Generated by Django 5.2.8 on 2026-02-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_duecollection_duesell'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdelivery',
            name='priojon_offer',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Priojon offer amount for the order', max_digits=12),
        ),
    ]
