# Generated by Django 5.2.8 on 2026-02-10 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_orderdelivery_priojon_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='duesell',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Order associated with this due sell', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_due_sells', to='sales.orderdelivery'),
        ),
    ]
