# Generated by Django 5.2.8 on 2026-02-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_duesell_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='damageorderitem',
            name='inventory_damage_deduction_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Inventory damage deduction as percentage (e.g., 10.50 for 10.5%)', max_digits=5),
        ),
    ]
