# Generated by Django 5.2.8 on 2026-03-31 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0019_add_inventory_damage_deduction_percent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="shift",
        ),
    ]
