# Generated by Django 5.2.8 on 2026-04-29 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_add_due_report_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='duecollection',
            new_name='sales_dueco_custome_7ff029_idx',
            old_name='sales_dueco_custome_0395f4_idx',
        ),
        migrations.RenameIndex(
            model_name='duesell',
            new_name='sales_duese_custome_20b1a7_idx',
            old_name='sales_duesel_custome_286da7_idx',
        ),
    ]
