# Generated by Django 5.2.8 on 2026-01-03 15:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('brand_address', models.CharField(blank=True, max_length=1255, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('IN_ACTIVE', 'In Active')], default='ACTIVE', max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('representative_name', models.CharField(blank=True, max_length=255, null=True)),
                ('representative_contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(max_length=255)),
                ('brand_address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('IN_ACTIVE', 'In Active')], default='ACTIVE', max_length=50)),
                ('representative_name', models.CharField(blank=True, max_length=255, null=True)),
                ('representative_contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('due_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_note', models.TextField(blank=True, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('have_offer', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('IN_ACTIVE', 'In Active'), ('PENDING', 'Pending')], default='PENDING', max_length=50)),
                ('sku', models.CharField(max_length=150)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_date', models.DateField(help_text='Date of the purchase')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount of the purchase', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_amount', models.DecimalField(decimal_places=2, help_text='Amount paid for this purchase', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('due_amount', models.DecimalField(decimal_places=2, help_text='Amount due for this purchase', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DUE', 'Due'), ('PAID', 'Paid')], default='PENDING', help_text='Status of the purchase', max_length=50)),
                ('note', models.TextField(blank=True, help_text='Additional notes for this purchase', null=True)),
                ('voucher_number', models.CharField(blank=True, help_text='Voucher number for this purchase', max_length=150, null=True)),
                ('supplier', models.ForeignKey(help_text='Supplier for this purchase', on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='product.supplier')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_for', models.CharField(choices=[('PRODUCT', 'Product'), ('PURCHASE', 'Purchase'), ('OFFER', 'Offer')], default='PRODUCT', help_text='Type of price (Product, Purchase, Offer)', max_length=50)),
                ('ctn_size', models.IntegerField(blank=True, help_text='Carton size', null=True)),
                ('ctn_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price per carton', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('piece_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price per piece', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, help_text='Special offer price', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_latest', models.BooleanField(default=True, help_text='Whether this is the latest price for this product and price type')),
                ('product', models.ForeignKey(help_text='Product this price belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Price',
                'verbose_name_plural': 'Product Prices',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'price_for', 'is_latest'], name='product_pro_product_9f4b3b_idx'), models.Index(fields=['is_latest'], name='product_pro_is_late_d91440_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_latest', True)), fields=('product', 'price_for'), name='unique_latest_price_per_product_type')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(help_text='Quantity of the product', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, help_text='Total price (quantity * unit_price)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(choices=[('CTN', 'CTN'), ('PICs', 'PICs')], help_text='Unit of measurement', max_length=50)),
                ('product', models.ForeignKey(help_text='Product in this purchase item', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='product.product')),
                ('purchase', models.ForeignKey(help_text='Purchase this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.purchase')),
            ],
            options={
                'verbose_name': 'Purchase Item',
                'verbose_name_plural': 'Purchase Items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['purchase', 'product'], name='product_pur_purchas_d71d01_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['supplier', 'purchase_date'], name='product_pur_supplie_ca97c4_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['status'], name='product_pur_status_351a8c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['voucher_number'], name='product_pur_voucher_d1dd73_idx'),
        ),
    ]
