# Generated by Django 5.2.8 on 2025-12-28 05:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('brand_address', models.CharField(blank=True, max_length=1255, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('IN_ACTIVE', 'In Active')], default='ACTIVE', max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('representative_name', models.CharField(blank=True, max_length=255, null=True)),
                ('representative_contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('ctn_size', models.IntegerField(blank=True, null=True)),
                ('ctn_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pic_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('have_offer', models.BooleanField(default=False)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('IN_ACTIVE', 'In Active'), ('PENDING', 'Pending')], default='PENDING', max_length=50)),
                ('sku', models.CharField(max_length=150)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
