# Generated by Django 5.2.8 on 2025-12-30 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ctn_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ctn_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pic_price',
        ),
    ]
