# Generated by Django 5.2.8 on 2026-01-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_buy_qty_product_free_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
