# Generated by Django 5.2.8 on 2025-12-30 17:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_ctn_price_remove_product_ctn_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_for', models.CharField(choices=[('RETAIL', 'Retail'), ('WHOLESALE', 'Wholesale'), ('BULK', 'Bulk')], default='RETAIL', help_text='Type of price (Retail, Wholesale, Bulk)', max_length=50)),
                ('ctn_size', models.IntegerField(blank=True, help_text='Carton size', null=True)),
                ('ctn_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price per carton', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('piece_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price per piece', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, help_text='Special offer price', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_latest', models.BooleanField(default=True, help_text='Whether this is the latest price for this product and price type')),
                ('product', models.ForeignKey(help_text='Product this price belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='product.product')),
            ],
            options={
                'verbose_name': 'Product Price',
                'verbose_name_plural': 'Product Prices',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'price_for', 'is_latest'], name='product_pro_product_9f4b3b_idx'), models.Index(fields=['is_latest'], name='product_pro_is_late_d91440_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_latest', True)), fields=('product', 'price_for'), name='unique_latest_price_per_product_type')],
            },
        ),
    ]
