# Generated by Django 5.2.8 on 2025-12-30 19:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(max_length=255)),
                ('brand_address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('IN_ACTIVE', 'In Active')], default='ACTIVE', max_length=50)),
                ('representative_name', models.CharField(blank=True, max_length=255, null=True)),
                ('representative_contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('due_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_note', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='productprice',
            name='price_for',
            field=models.CharField(choices=[('PRODUCT', 'Product'), ('PURCHASE', 'Purchase'), ('OFFER', 'Offer')], default='PRODUCT', help_text='Type of price (Product, Purchase, Offer)', max_length=50),
        ),
    ]
