# Generated by Django 5.2.8 on 2025-12-30 19:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_supplier_alter_productprice_price_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='payment_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_date', models.DateField(help_text='Date of the purchase')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount of the purchase', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_amount', models.DecimalField(decimal_places=2, help_text='Amount paid for this purchase', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('due_amount', models.DecimalField(decimal_places=2, help_text='Amount due for this purchase', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DUE', 'Due'), ('PAID', 'Paid')], default='PENDING', help_text='Status of the purchase', max_length=50)),
                ('note', models.TextField(blank=True, help_text='Additional notes for this purchase', null=True)),
                ('voucher_number', models.CharField(blank=True, help_text='Voucher number for this purchase', max_length=150, null=True)),
                ('supplier', models.ForeignKey(help_text='Supplier for this purchase', on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='product.supplier')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(help_text='Quantity of the product', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, help_text='Total price (quantity * unit_price)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(choices=[('CTN', 'CTN'), ('PICs', 'PICs')], help_text='Unit of measurement', max_length=50)),
                ('product', models.ForeignKey(help_text='Product in this purchase item', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='product.product')),
                ('purchase', models.ForeignKey(help_text='Purchase this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.purchase')),
            ],
            options={
                'verbose_name': 'Purchase Item',
                'verbose_name_plural': 'Purchase Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['supplier', 'purchase_date'], name='product_pur_supplie_ca97c4_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['status'], name='product_pur_status_351a8c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['voucher_number'], name='product_pur_voucher_d1dd73_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['purchase', 'product'], name='product_pur_purchas_d71d01_idx'),
        ),
    ]
