# Generated by Django 5.2.8 on 2026-01-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sales_commission_in_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
