# Generated by Django 5.2.8 on 2026-01-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0003_alter_workingday_options'),
        ('user', '0002_profile_sales_commission_in_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='zone',
        ),
        migrations.AddField(
            model_name='profile',
            name='areas',
            field=models.ManyToManyField(related_name='profiles_areas', to='area.area'),
        ),
        migrations.AddField(
            model_name='profile',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
