# Generated by Django 5.2.8 on 2025-12-31 01:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0005_alter_supplier_payment_note_purchase_purchaseitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Stock Type',
                'verbose_name_plural': 'Stock Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], help_text='Type of transaction: IN or OUT', max_length=20)),
                ('have_transfer', models.BooleanField(default=False, help_text='Whether this transaction involves a transfer')),
                ('note', models.TextField(blank=True, help_text='Additional notes about the transaction')),
                ('price', models.ForeignKey(help_text='Price reference for this transaction', on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='product.productprice')),
                ('product', models.ForeignKey(help_text='Product involved in the transaction', on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='product.product')),
                ('stock_type', models.ForeignKey(help_text='Type of stock location/category', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.stocktype')),
                ('transfer_from', models.ForeignKey(blank=True, help_text='Source stock type for transfer (if applicable)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='inventory.stocktype')),
                ('transfer_to', models.ForeignKey(blank=True, help_text='Destination stock type for transfer (if applicable)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='inventory.stocktype')),
            ],
            options={
                'verbose_name': 'Stock Transaction',
                'verbose_name_plural': 'Stock Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stock_type', 'transaction_type'], name='inventory_s_stock_t_a05ef2_idx'), models.Index(fields=['product'], name='inventory_s_product_94c743_idx'), models.Index(fields=['created_at'], name='inventory_s_created_ff5dbb_idx')],
            },
        ),
    ]
