# Generated by Django 5.2.8 on 2026-01-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Batch number for this transaction', max_length=100, null=True),
        ),
    ]
