# Generated by Django 5.2.8 on 2025-12-31 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='ctn_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Carton quantity for this transaction'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='piece_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Piece quantity for this transaction'),
        ),
    ]
