# Generated by Django 5.2.8 on 2026-01-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stocktransaction_batch_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransaction',
            name='price',
        ),
    ]
