# Generated by Django 5.2.8 on 2026-01-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_stocktransaction_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Unit price for this transaction', max_digits=10),
        ),
    ]
