# Generated by Django 5.2.8 on 2026-01-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stocktransaction_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransaction',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='ctn_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Carton price for this transaction', max_digits=10),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='piece_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Piece price for this transaction', max_digits=10),
        ),
    ]
