# Generated by Django 5.2.8 on 2026-01-27 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_stocktransaction_unit_price_and_more'),
        ('product', '0003_alter_product_sku'),
        ('sales', '0011_remove_orderitem_damaged_in_ctn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='order_item',
            field=models.ForeignKey(blank=True, help_text='Order item for this transaction', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='sales.orderitem'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='product_price',
            field=models.ForeignKey(blank=True, help_text='Product price for this transaction', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='product.productprice'),
        ),
    ]
