# Generated by Django 5.2.8 on 2026-02-04 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stocktransaction_order_item_and_more'),
        ('sales', '0014_remove_orderdelivery_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='damage_order_item',
            field=models.ForeignKey(blank=True, help_text='Damage order item for this transaction', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='sales.damageorderitem'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='free_offer_item',
            field=models.ForeignKey(blank=True, help_text='Free offer item for this transaction', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='sales.freeofferitem'),
        ),
    ]
