# Generated by Django 5.2.8 on 2026-02-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stocktransaction_damage_order_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransaction',
            name='product_price',
        ),
    ]
