# Generated by Django 5.2.8 on 2026-02-18 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_product_price'),
        ('product', '0003_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='product_price',
            field=models.ForeignKey(blank=True, help_text='Product price for this transaction', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='product.productprice'),
        ),
    ]
