# Generated by Django 5.2.8 on 2026-01-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='have_special_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='special_discount_in_persentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
