# Generated by Django 5.2.8 on 2026-01-12 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0003_alter_workingday_options'),
        ('crm', '0002_customer_have_special_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='zone',
        ),
        migrations.AddField(
            model_name='customer',
            name='area',
            field=models.ForeignKey(blank=True, help_text='Area where the customer is located', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='area.area'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='fridge_type',
            field=models.CharField(blank=True, choices=[('PDF', 'PDF'), ('ODF', 'ODF')], max_length=50, null=True),
        ),
    ]
