# Generated by Django 5.2.8 on 2026-02-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_customer_zone_customer_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='shop_name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
