# Generated by Django 5.2.8 on 2026-01-01 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['name'], 'verbose_name': 'Zone', 'verbose_name_plural': 'Zones'},
        ),
    ]
