# Generated by Django 5.2.8 on 2026-01-12 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0002_workingday_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workingday',
            options={'ordering': ['name'], 'verbose_name': 'Working Day', 'verbose_name_plural': 'Working Days'},
        ),
    ]
